### ISSUE TITLE
Succesfully loading projects only with admin rights

### ISSUE THREAD

**Issue by ryzhov22** [conveniencable/RedmineConnectorRelease#1]
Hello!
It is weird but having admin rights is the only way to use plugin on all accessible projects (in Redmine for user).
Otherwise the user without admin rights can't reach some projects with which he can work in Redmine

**Comment by conveniencable** [comment]
Sorry for not testing the not-admin users.
Please pull the newest codes from https://github.com/conveniencable/microsoft_project_connector for your redmine installation.
