### ISSUE TITLE
How use it?

### ISSUE THREAD

**Issue by wfion** [conveniencable/RedmineConnectorRelease#5]
I run RedmineConnector.vtso
System.Deployment.Application.DeploymentDownloadException: download
file:///C:/Users/Administrator/AppData/Roaming/conveniencable.com/Microsoft Project Redmine Connector/arm64/WebView2Loader.dll

OS: windows11 21H2
Office: Microsoft® Excel® 适用于 Microsoft 365 MSO (16.0.14131.20326) 64 位
CPU: i5-4210M

**Comment by zinpetrenko** [comment]
There is a little tutorial https://conveniencable.com/
P.S. Excel and Project are not the same things.

**Comment by wfion** [comment]
> There is a little tutorial https://conveniencable.com/
> P.S. Excel and Project are not the same things.

Hello,
Yes, isn't this plug-in enabled in Office? 
 can’t find anything to enable it in Office.

**Comment by wfion** [comment]
https://conveniencable.com/documents/msProject
`
If your office(Not Windows OS) is X86, download the X86 file, else download the X64 file. 
First, your computer must be online while the installation may download dependencies(.net framework and vsto runtime) from internet.
`
My computer is online...

**Comment by wfion** [comment]
I setup Microsoft Edge Webview2 Runtime.
I don't know if my environment installation meets the requirements? 
![20210813163802.png](https://i.loli.net/2021/08/13/9JQHjchyvClgu7r.png)
Thank you for your answer

**Comment by wfion** [comment]
Hello,
The issue hope to help you
