### ISSUE TITLE
cannot connect to register server

### ISSUE THREAD

**Issue by derevyov** [conveniencable/RedmineConnectorRelease#6]
cannot connect to register server
my pc have a proxy. 
how i can connection to register server?

**Comment by conveniencable** [comment]
Can your PC access https://conveniencable.com? Can you provide information of "ping conveniencable.com" on your PC?

**Comment by conveniencable** [comment]
> 
> 
> cannot connect to register server my pc have a proxy. how i can connection to register server?

Can your PC access https://conveniencable.com? 
Can you provide information of "ping conveniencable.com" on your PC?

**Comment by derevyov** [comment]
From my browser everything is ok. And from MsProject I can't see the captcha
