### ISSUE TITLE
bad installer, no source code

### ISSUE THREAD

**Issue by gunslnger42** [conveniencable/RedmineConnectorRelease#8]
The installer triggers anti-virus warnings, and apparently the source code zip is empty, so I can't build it myself.

**Comment by conveniencable** [comment]
Sorry, this repository is for publishing the installer, and I can't publish the source code for some reasons.
Many anti-virus software reject apps not because they contains virus but just because they don't contains a certificate from famous company.

**Comment by gunslnger42** [comment]
I've seen installers add malware themselves.  Maybe use a different installer?  I've had good results with Inno Setup.
![image](https://user-images.githubusercontent.com/95984700/147285799-9980f57c-6204-426f-88f0-93a9778b493d.png)

**Comment by conveniencable** [comment]
It's caused by the self-signed certificate. I google and find some similar issues when the C# developer obfuscate their code and signed with a self-signed certificate. Now a day, allmost all of the anti-virus reject all the softwares which contain an unpaied certificate.
